#AndroidIDE: enforce UTF-8 & locale for Gradle daemon
#Thu Nov 27 00:09:45 GMT 2025
android.nonTransitiveRClass=true
systemProp.user.language=en
systemProp.user.country=US
systemProp.kotlin.daemon.client.alive.path=/storage/emulated/0/AndroidIDEProjects/_gradle_tmp/kotlin-daemon.alive
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding\=UTF-8
android.enableAapt2Daemon=false
android.useAndroidX=true
android.suppressUnsupportedCompileSdk=35
kotlin.code.style=official
ksp.incremental=false
systemProp.java.io.tmpdir=/storage/emulated/0/AndroidIDEProjects/_gradle_tmp
org.gradle.workers.max=2
android.defaults.buildfeatures.buildconfig=true
systemProp.sun.jnu.encoding=UTF-8
android.nonFinalResIds=false
systemProp.file.encoding=UTF-8
